- name: Add some security rules to the firewall
  hosts: localhost
  connection: local
  gather_facts: False

#  roles:
#    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'var.yml'
    no_log: 'yes'

  - name: Add test rule 1 to the firewall
    panos_security_rule:
      ip_address: '192.168.0.224'
      username: 'admin'
      password: 'admin'
      operation: 'add'
      rule_name: 'Ansible_Test_Fil'
      description: 'An Ansible test rule'
      source_zone: ['any']
      destination_zone: ['any']
      source_ip: ['1.2.3.4']
      source_user: ['any']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-http']
      hip_profiles: ['any']
      action: 'allow'
      commit: 'True'
